import React, { useRef } from 'react';
import { Download, AlertTriangle, Info, ShieldAlert, CheckCircle, FileText } from 'lucide-react';
import { motion } from 'framer-motion';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export default function ReportSection({ report }) {
  const reportRef = useRef();

  const handleExportPDF = async () => {
    const element = reportRef.current;
    if (!element) return;
    
    // Quick and simple PDF generation
    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save('Detailed-Diagnostic-Report.pdf');
  };

  if (!report) return null;

  const renderSection = (title, content, Icon, colorClass) => {
    if (!content || content.length === 0 || content === "Not Available") {
      return (
        <div className="mb-6 bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
          <h3 className={`text-xl font-bold flex items-center mb-3 ${colorClass}`}>
            <Icon className="w-6 h-6 mr-2" /> {title}
          </h3>
          <p className="text-gray-400 italic">Not Available</p>
        </div>
      );
    }
    
    return (
      <motion.div 
        initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }}
        className="mb-6 bg-white p-6 rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow"
      >
        <h3 className={`text-xl font-bold flex items-center mb-4 pb-2 border-b border-gray-100 ${colorClass}`}>
          <Icon className="w-6 h-6 mr-2" /> {title}
        </h3>
        {Array.isArray(content) ? (
          <ul className="space-y-3">
            {content.map((item, idx) => (
              <li key={idx} className="flex items-start">
                <div className={`mt-1 h-2 w-2 rounded-full ${colorClass.split(' ')[0].replace('text-', 'bg-')} mr-3 flex-shrink-0`}></div>
                <span className="text-gray-700 leading-relaxed">
                  {typeof item === 'object' ? (
                    <div>
                      <strong>{item.area}:</strong> {item.observation}
                      {item.image && item.image !== "Image Not Available" && (
                        <div className="mt-2 text-sm text-blue-500 italic max-w-sm rounded bg-gray-50 p-2 border border-gray-200 flex items-center">
                           <FileText className="w-4 h-4 mr-1"/> Referenced Image: {item.image}
                        </div>
                      )}
                    </div>
                  ) : item}
                </span>
              </li>
            ))}
          </ul>
        ) : (
          <div className="text-gray-700 leading-relaxed whitespace-pre-wrap">{content}</div>
        )}
      </motion.div>
    );
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-3xl font-extrabold text-gray-900">Diagnostic Report</h2>
        <button 
          onClick={handleExportPDF}
          className="flex items-center px-4 py-2 bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition shadow"
        >
          <Download className="w-5 h-5 mr-2" /> Export PDF
        </button>
      </div>

      <div ref={reportRef} className="bg-gray-50 p-8 rounded-2xl shadow-inner border border-gray-200">
        <div className="text-center mb-10 pb-6 border-b-2 border-gray-200">
          <h1 className="text-4xl font-black tracking-tight text-gray-900 uppercase">UrbanRoof DDR</h1>
          <p className="text-gray-500 mt-2 font-medium">Detailed Diagnostic Report generated by AI</p>
        </div>

        {renderSection("1. Property Issue Summary", report["Property Issue Summary"], AlertTriangle, "text-red-600")}
        {renderSection("2. Area-wise Observations", report["Area-wise Observations"], Info, "text-blue-600")}
        {renderSection("3. Probable Root Cause", report["Probable Root Cause"], ShieldAlert, "text-orange-600")}
        {renderSection("4. Severity Assessment", report["Severity Assessment"], AlertTriangle, "text-red-700")}
        {renderSection("5. Recommended Actions", report["Recommended Actions"], CheckCircle, "text-green-600")}
        {renderSection("6. Additional Notes", report["Additional Notes"], FileText, "text-gray-700")}
        {renderSection("7. Missing or Unclear Information", report["Missing or Unclear Information"], Info, "text-purple-600")}
      </div>
    </div>
  );
}
